function dat = import_field_plane_COMSOL(filename, dataLines)
%IMPORTFILE Import data from a text file
%  COILGXPLANE = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  COILGXPLANE = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  coilgxplane = importfile("D:\Dropbox (UFL)\school\dissertation\Simulation\gx_homogeneity\coil_gx_plane.txt", [10, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 16-Jun-2023 02:45:41

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [10, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "Model", "coil_gx_saddle_perturbed_squarearea__dissertationmph"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
dat = readtable(filename, opts);

%% Convert to output type
dat = table2array(dat);
end